### ISSUE TITLE
Should not run code when Transport is disabled

### ISSUE THREAD

**Issue by Gennon** [Chykary/FizzySteamworks#13]
Hi,
I was testing the Transport, but wanted to disabled it for some builds etc. 
However, by disabling the component it was still running some code that requires Steam to be running. 
I had to add the following code in the Awake function:

`if(!enabled) { return; }`

I think this should be a feature in this transport anyway. 

Thanks for you work!

**Comment by Chykary** [comment]
Thank you! Fixed in the latest release. :-)
