### ISSUE TITLE
when i imported it unity rec version 2020.3

### ISSUE THREAD

**Issue by coolst3rs1** [Chykary/FizzySteamworks#14]
public override void ServerDisconnect(int connectionId)

**Comment by Jacykow** [comment]
Same here
`Assets\Mirror\Runtime\Transport\FizzySteamworks\FizzySteamworks.cs(210,26): error CS0508: 'FizzySteamworks.ServerDisconnect(int)': return type must be 'bool' to match overridden member 'Transport.ServerDisconnect(int)'`

**Comment by xzessmedia** [comment]
Error Stack tells all, just change to this

`public override bool ServerDisconnect(int connectionId)
    {
      if (ServerActive())
      {
        server.Disconnect(connectionId);
      }

      return true;
    }`

**Comment by Chykary** [comment]
Yeah, the transport is already updated to a newer Mirror version as said in the release notes. Please use a previous version of the transport until the latest Mirror is pushed to asset store :)
