### ISSUE TITLE
Can you give me a little tutorial?

### ISSUE THREAD

**Issue by blfc1122** [Chykary/FizzySteamworks#23]
I'm currently learning mirror and I'm almost done.
I'm trying to link a multiplayer game to Steam, and I've been looking around, but I have no idea how to do it, can you give me a simple example? If it's not convenient to give a complete one, you can just tell me some key code, like how to link a steam socket to mirror, etc.
Thanks！

**Comment by blfc1122** [comment]
Please！

**Comment by blfc1122** [comment]
Who can save me？

**Comment by LukeSeers** [comment]
Just read the https://github.com/Chykary/FizzySteamworks/blob/master/README.md It's pretty straight forward and it holds your hand.

**Comment by rafaeldolfe** [comment]
I think it is reasonable to want one elaboration though which is expanding on what is meant by 

> In your "NetworkManager" object replace "KCP" with "FizzySteamworks".

Can someone specify? Which NetworkManager? A script instantiated on a gameobject, or the script itself? And which KCPs?

**Comment by LukeSeers** [comment]
Sorry I have not touched this in a long while. So, I wont be as useful. @Chykary Updated the readme from a pull request fairly recently, so they'll be the one to hopefully know more.

**Comment by Chykary** [comment]
Imo that's a Mirror doc thing. This transport works like any other transport. Here's the link to the Mirror doc: https://mirror-networking.gitbook.io/docs/transports

Mirror uses a NetworkManager Script which contains a reference to a used transport. There you drop in this transport (FizzySteamworks), and connect to the SteamID of a user who is hosting. That's all!

**Comment by rafaeldolfe** [comment]
That explanation makes sense @Chykary. I had previously followed a tutorial on Mirror but still missed the meaning behind the sentence. Perhaps changing it to 
> In your "NetworkManager" GameObject change the "Transport" reference from KCP to FizzySteamworks.
will help people who are new to these tools.
