### ISSUE TITLE
Release out of date

### ISSUE THREAD

**Issue by JamesMcGhee** [Chykary/FizzySteamworks#24]
Your release package is out of date from the current state of the code on master.

Also happy to help get this project set to use package manager if you would like, this would remove the need to package a release unitypackage up saving you a step and insuring people are on the latest by simply running the in Unity package manager

**Comment by andrewspalato** [comment]
Bump, at some point Mirror and FizzySteamworks crash the player when a client connects. 

Will need to roll back Mirror if FizzySteamworks isn't updated soon.

`Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.`

**Comment by JamesMcGhee** [comment]
The package is still out of data

What we recomend our user's do is download the code from the green Code button on the Code page as a zip, copy the required files into Unity

Seems to work fine that way
I would happily update the release for you if I had the rights but I do not

**Comment by JamesMcGhee** [comment]
This issue is now resolved with the latest release update
