### ISSUE TITLE
Crash when connects, I went back to a working commit and the same error still occurs.

### ISSUE THREAD

**Issue by Pordrack** [Chykary/FizzySteamworks#26]
Hello, I am trying to make a multiplayer game with steam, so I'm currently using Mirror and FizzySteamworks. After following the DapperDino tutorial, everything worked. I went a little further, and nothing worked, so I came back few commits backward to when it was still working an I still have the same mistakes which is blowing my mind, here's the error I'm getting Server and Client side : https://cdn.discordapp.com/attachments/775305953922252810/908774217904971816/unknown.png
https://cdn.discordapp.com/attachments/775305953922252810/908774366387535942/unknown.png

**Comment by JamesMcGhee** [comment]
In general your better off getting support on the Discord channel for this transport.

https://discord.gg/XXWRwf2kNd

Listing the exception returned and the steps you tool there should help them give you better guidance
