### ISSUE TITLE
Steam friends server browser guidance?

### ISSUE THREAD

**Issue by GrecuAlexandru** [Chykary/FizzySteamworks#32]
First of all, I'm sorry for asking it here as an issue!

I want to create a Steam friends server browser, which, as it says, it displays the **client-hosted** servers created by my friends. This is my second day of just research in this matter and I am not able to connect any dots. I have looked through:

- FizzySteamworks README
- Steamworks.NET Docs and examples (Steamworks.NET Example/Steamworks.NET Test). Yes, I went through the code.
- Steamworks Official Docs
- FizzySteamworks code
- Any possible tutorial there is..

I managed to make the Mirror's **NetworkManager** work using **FizzySteamworks** as the transport. Managed to Host/Join using **User Steam ID** (using the default HUD Mirror provides in the Unity package). Managed to make players sync movement and rotation.
I saw that in the **Steamworks.NET Test** project, I can create and join a lobby.

What I would like to know:

1. Looking at the default **NetworkManagerHUD**, does the Host button create a Server(**SteamMatchmakingServers**) or a Lobby(**SteamMatchmaking**)?
2. Assuming it creates a server, how do I get a list of servers my friends host?
3. How do I give that server a **name and a password**?

I have more questions, but they all depend on whether or not the button creates a server or a lobby.

**Comment by Chykary** [comment]
Matchmaking / Lobbies are not the responsibility/part of the transport :)
