### ISSUE TITLE
Connection was closed by peer, Timed out attempting to connect.

### ISSUE THREAD

**Issue by IndiaGameMaker** [Chykary/FizzySteamworks#39]
Hi, I don't know when this problem has been with me since.
I have tried to modify FizzySteamworks.Timeout but it doesn't solve the problem.
But there is one thing, sometimes this problem does not occur, but most of the time it is not linked to the host.
I hope you can answer it directly here, there are too many people in Discover and I don't think anyone cares about my problem.
Thank you very much!

![image](https://user-images.githubusercontent.com/1924146/174516341-e682e4ee-d87f-43cf-aaf1-9032cfd5727d.png)

**Comment by dpcco** [comment]
can you solve this problem?

**Comment by KylaCpper** [comment]
I also have this problem with my desktop, not with notebook, it's strange

**Comment by sb30930638383** [comment]
Try removing the other types of Transport script from the NetworkManager object, leaving only FizzySteamworks

**Comment by sb30930638383** [comment]
Try removing the other types of Transport script from the NetworkManager object, leaving only FizzySteamworks @blfc1122 @dpcco @KylaCpper
