### ISSUE TITLE
Update to latest Heathen's Steamworks Foundaiton version

### ISSUE THREAD

**Issue by WeLoveGaming** [Chykary/FizzySteamworks#40]
Hello.
FizzySteamworks does not support the latest version of Steamworks Foundaiton since my console is being spammed with errors saying that Steamworks could not be found even after I installed it.
Please update FizzySteamworks to work with the latest version of Steamworks Foundaiton, thanks.
![Capture](https://user-images.githubusercontent.com/34948795/175134346-b6f45986-97c7-459d-b393-e449b10b144a.PNG)

**Comment by Vandora-41** [comment]
hey did you fix this?

**Comment by RatCaptain** [comment]
Hi!
I have the same problem.
Did you fixed it some how ?

**Comment by mhipszer** [comment]
same issue as above  running unity 2021.3.11 and with mirror 2022.9.15 fuzzy version 4.4

**Comment by dgb1110101** [comment]
Similar errors:
Assets\Mirror\Runtime\Transports\FizzySteamworks\LegacyServer.cs(14,35): error CS0246: The type or namespace name 'TransportError' could not be found (are you missing a using directive or an assembly reference?)

Assets\Mirror\Runtime\Transports\FizzySteamworks\NextServer.cs(14,35): error CS0246: The type or namespace name 'TransportError' could not be found (are you missing a using directive or an assembly reference?)

Versions:
FizzySteamworks: 5.1
Unity: 2021.3.11
Mirror: 2022.10.0

**Comment by sythel** [comment]
did you install steamworks or heathen
