### ISSUE TITLE
Have you guys found "Use Next Gen Steam Networking" makes connection extremly unstable?

### ISSUE THREAD

**Issue by Rigidbody911** [Chykary/FizzySteamworks#50]
Although valve are saying they will remove the old solution soon, using next gen steam networking has a high chance disconnecting players from fragile steam p2p connection, while untick the toggle makes the connection a lot more stable.

For example it will through "Connection was closed by peer, Timed out attempting to connect" frequently.

 Recently another problem tirggered me mad, that in the Steam lobby meta data, I am using a string called "password" to store the password of player's lobbies, an issue occurred for a week that the password function is not working anymore, after hours of debugging I found that Valve auto changed 'p' to  uppercase 'P' in the background, which is pretty ridiculous, shouldn't they fix this bug which has been added randomly?  I guess they are on vacation now.

Personally  I plan to stick to the old networking solution until Valve abandon them. Hope this help those who are getting bothered by related problems.

**Comment by bjornthefire** [comment]
I noticed that with the old solution my ping is 1/3 - 1/2 as what it is with the new solution when testing
