### ISSUE TITLE
Latest Release Missing files?

### ISSUE THREAD

**Issue by ErencanPelin** [Chykary/FizzySteamworks#51]
Hi there! I was just following a YT tut on getting this setup, I downloaded the last Unity Package shown in releases (v5.1) and after importing it to unity it only imported a few scripts. The tutorial I was using is a few years old now, and was using version 2.5.2. I downloaded the older release and sure enough it contained all the files I needed. Just pointing this out as I'm not sure if this is expected behaviour or not. It should be noted that Steamworks.NET stuff were the majority of the missing and causing the package from not working properly!

**Comment by MrGadget1024** [comment]
Steamworks is no longer included with Fizzy - get the latest directly from the source as described in the ReadMe.
