### ISSUE TITLE
Channels except reliable don't seem to work

### ISSUE THREAD

**Issue by deltapilot** [Chykary/FizzySteamworks#6]
Ive only tested this with RPCs but setting any of the channels to unreliable and then using it with an RPC call doesnt seem to fire the RPC at the other end. However, changing the channel type back to reliable works. So for example if i set an rpc to use channel 2, if channel to is reliable it works, if its unreliable it doesnt.

**Comment by Chykary** [comment]
Mirror Bug: https://github.com/vis2k/Mirror/issues/1858
