### ISSUE TITLE
New Mirror ClientSend and ServerSend

### ISSUE THREAD

**Issue by Polocapt** [Chykary/FizzySteamworks#9]
Hi just wanted to let you know that in the new Mirror version, the return type of the ServerSend and ClientSend is now void, hence breaking the Transport FizzySteamWorks override. Also ServerSend now return only 1 connection id instead of the list

**Comment by Hangeris** [comment]
Just wanted to provide some more information.

These are the errors on Unity 2020.1.15f1 after installing Mirror(26.2.2) and FizzySteamworks(v2.6):
1. Assets\Mirror\Runtime\Transport\FizzySteamworks\FizzySteamworks.cs(105,30): error CS0508: 'FizzySteamworks.ClientSend(int, ArraySegment<byte>)': return type must be 'bool' to match overridden member 'Transport.ClientSend(int, ArraySegment<byte>)'
2. Assets\Mirror\Runtime\Transport\FizzySteamworks\FizzySteamworks.cs(163,30): error CS0115: 'FizzySteamworks.ServerSend(int, int, ArraySegment<byte>)': no suitable method found to override
3. Assets\Mirror\Runtime\Transport\FizzySteamworks\FizzySteamworks.cs(11,18): error CS0534: 'FizzySteamworks' does not implement inherited abstract member 'Transport.ServerSend(List<int>, int, ArraySegment<byte>)'

**Comment by AliTsuki** [comment]
Using Unity 2020.1.15f1 with Mirror 26.2.2 and FizzySteamworks 2.6, I noticed the same errors and made the following changes.

in Assets\Mirror\Runtime\Transport\FizzySteamworks\FizzySteamworks.cs
I changed ClientSend() to:

`        public override bool ClientSend(int channelId, ArraySegment<byte> segment)
        {
            byte[] data = new byte[segment.Count];
            Array.Copy(segment.Array, segment.Offset, data, 0, segment.Count);
            client.Send(data, channelId);
            return true;
        }
`

and changed ServerSend() to:
`        public override bool ServerSend(List<int> connectionIds, int channelId, ArraySegment<byte> segment)
        {
            if (ServerActive())
            {
                byte[] data = new byte[segment.Count];
                Array.Copy(segment.Array, segment.Offset, data, 0, segment.Count);
                // send to all
                bool result = true;
                foreach(int connectionId in connectionIds)
                    result &= server.SendAll(connectionId, data, channelId);
                return result;
            }
            return false;
        }
`

and in Assets\Mirror\Runtime\Transport\FizzySteamworks\Server.cs
I changed SendAll() to:
`        public bool SendAll(int connectionId, byte[] data, int channelId)
        {
            if (steamToMirrorIds.TryGetValue(connectionId, out CSteamID steamId))
            {
                Send(steamId, data, channelId);
                return true;
            }
            else
            {
                Debug.LogError("Trying to send on unknown connection: " + connectionId);
                OnReceivedError.Invoke(connectionId, new Exception("ERROR Unknown Connection"));
                return false;
            }
        }
`

That should get rid of those errors without breaking anything, but I don't have the time to test at the moment.

**Comment by Chykary** [comment]
Should not occur with a current Mirror and Fizzy version. The 2.6 release was to address this issue.
